language: php
dist: xenial

services:
  - mysql

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"

php:
  - 7.3

branches:
  only:
    - /^8\.([0-9]+|x)\-[0-9]+\.([0-9]+|x)$/

env:
  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin"
    - COMPOSER_MEMORY_LIMIT=-1
    - DRUPAL_TRAVIS_TEST_DEPRECATION=false

matrix:
  include:
    - env: DRUPAL_TRAVIS_DRUPAL_VERSION=9.0.x-dev
    - env: DRUPAL_TRAVIS_DRUPAL_VERSION=~8.8.0
      php: 7.2
    - env: DRUPAL_TRAVIS_DRUPAL_VERSION=~8.8.0


before_install:
  - composer global require thunder/travis:dev-drupal9

install:
  - test-drupal-project prepare_build
  - composer require npm-asset/select2:^4.0.7 --no-update  --working-dir=/tmp/test/select2/install

script:
  - test-drupal-project

notifications:
  email: false
